export { default as PagesLang } from './languages'
export { default as WellcomePage } from './WellcomePage'
export { default as PlayersPage } from './PlayersPage'
export { default as GamePage } from './GamePage'
export { default as LeaderboardPage } from './LeaderboardPage'